Filter topics out based on committer
Box-Castle/committer-api pull request #2
Opened 2017-07-08 01:49 UTC by bharathi-ravishanker

2017-07-08 01:54 UTC, bharathi-ravishanker commented
Initial commit without tests @denisgrenader

2017-07-08 05:18 UTC, denisgrenader requested changes

2017-07-08 05:18 UTC, denisgrenader commented on src/main/scala/com/box/castle/committer/api/CommitterFactory.scala
> +  def createFilter(): Filter = {
createTopicFilter(): TopicFilter

2017-07-08 05:18 UTC, denisgrenader commented on src/main/scala/com/box/castle/committer/api/FilterTopicsFactory.scala
> +class FilterTopicsFactory {
I don't think we need a separate factory for this

2017-07-08 05:18 UTC, denisgrenader commented on src/main/scala/com/box/castle/committer/api/Filter.scala
> +class Filter {
class TopicFilter {

2017-07-08 05:18 UTC, denisgrenader commented on src/main/scala/com/box/castle/committer/api/Filter.scala
> +  def containsTopic(topic: String): Boolean = {
def match(topic: String): Boolean

2017-07-10 20:14 UTC, denisgrenader approved these changes

2017-07-11 16:54 UTC, merged